name: Build

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Legge la versione dal file version.txt
      - name: Get App Version
        id: app_version
        shell: pwsh
        run: |
          $version = Get-Content version.txt -Raw
          $version = $version.Trim()
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Get Python version
        id: python-version
        run: |
          $pythonVersion = (python --version).Split(" ")[1]
          echo "version=$pythonVersion" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - name: Install build tools
        run: pip install pyinstaller pipreqs

      - name: Generate requirements.txt
        run: pipreqs --force .

      - name: Commit requirements.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'feat(build): update requirements.txt'
          file_pattern: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up UPX
        run: choco install upx -y

      - name: Build EXE
        run: pyinstaller DesktopIconBackupManager.spec

      - name: Create artifact folder
        shell: pwsh
        run: |
          mkdir artifact_contents
          move dist\DesktopIconBackupManager_*.exe artifact_contents/

      - name: Save ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: DesktopIconBackupManager-v${{ steps.app_version.outputs.version }}
          path: artifact_contents/

      - name: Create Release ZIP
        shell: pwsh
        run: Compress-Archive -Path artifact_contents/* -DestinationPath DesktopIconBackupManager.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: DesktopIconBackupManager.zip
          tag_name: v${{ steps.app_version.outputs.version }}
          name: Release v${{ steps.app_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}